[tool.poetry]
name = "integrate"
version = "0.1.0"
description = ""
authors = ["Andrew Panov <gooday358@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
